version: '3.8'

services:
  db:
    container_name: db
    ports:
      - "8000:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    image: postgres:14.5-alpine3.16


  backend:
    container_name: chat-backend
    image: saxez/chat-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - DB_PORT=8000
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=root
      - DB_NAME=postgres
    depends_on:
      - db


  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client/src:/client/src'
      - './client/public:/client/public'
    ports:
      - "5001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

    
  